### ISSUE TITLE
[PERFORMANCE] hardware continues integration needs a high RPM high tooth count test case

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1351]
CI on real hardware should assert 10K RPM at 60/2 with self-stimulation or smth :)

**Comment by rusefi** [comment]
Good news - it has properly reported issues at 8500 with engine type 32
```     [java] java.lang.IllegalStateException: Failed Got 27473.0 while trying to stay at 8500
     [java] 	at com.rusefi.AutoTest.assertRpmDoesNotJump(AutoTest.java:96)
     [java] 	at com.rusefi.AutoTest.testVW_60_2(AutoTest.java:80)
     [java] 	at com.rusefi.AutoTest.mainTestBody(AutoTest.java:55)
     [java] 	at com.rusefi.RealHwTest.runRealHardwareTest(RealHwTest.java:87)
     [java] 	at com.rusefi.RealHwTest.runHardwareTest(RealHwTest.java:51)
     [java] 	at com.rusefi.RealHwTest.runHardwareTest(RealHwTest.java:41)
     [java] 	at com.rusefi.RealHwTest.main(RealHwTest.java:24)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:218)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
     [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:861)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:231)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
     [java] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)

**Comment by rusefi** [comment]
stim_check 3000 5 30

would set RPM to 3000, give it 5 seconds to settle, and test for 30 seconds

**Comment by rusefi** [comment]
even with extra settle time :(

     [java] java.lang.IllegalStateException: Failed Got 4247.0 while trying to stay at 4000
     [java] 	at com.rusefi.AutoTest$2.apply(AutoTest.java:77)
     [java] 	at com.rusefi.AutoTest$2.apply(AutoTest.java:73)
     [java] 	at com.rusefi.AutoTest.assertRpmDoesNotJump(AutoTest.java:112)
     [java] 	at com.rusefi.AutoTest.testVW_60_2(AutoTest.java:87)
     [java] 	at com.rusefi.AutoTest.mainTestBody(AutoTest.java:53)
     [java] 	at com.rusefi.RealHwTest.runRealHardwareTest(RealHwTest.java:87)
     [java] 	at com.rusefi.RealHwTest.runHardwareTest(RealHwTest.java:51)
     [java] 	at com.rusefi.RealHwTest.runHardwareTest(RealHwTest.java:41)
     [java] 	at com.rusefi.RealHwTest.main(RealHwTest.java:24)

**Comment by rusefi** [comment]
```t1!u_38!5568!t1!d_39!5590!t1!u_40!5614!]
     [java] 2020-04-24_12_51_54_841<EOT>: Test failed: java.lang.IllegalStateException: Failed Got 1466.0 while trying to stay at 2200 at java.lang.IllegalStateException: Failed Got 1466.0 while trying to stay at 2200
     [java]     at com.rusefi.AutoTest$2.apply(AutoTest.java:77)
     [java]     at com.rusefi.AutoTest$2.apply(AutoTest.java:73)
     [java]     at com.rusefi.AutoTest.assertRpmDoesNotJump(AutoTest.java:112)
     [java]     at com.rusefi.AutoTest.testV12(AutoTest.java:95)
     [java]     at com.rusefi.AutoTest.mainTestBody(AutoTest.java:54)
     [java]     at com.rusefi.RealHwTest.runRealHardwareTest(RealHwTest.java:87)
     [java]     at com.rusefi.RealHwTest.runHardwareTest(RealHwTest.java:51)
     [java]     at com.rusefi.RealHwTest.runHardwareTest(RealHwTest.java:41)
     [java]     at com.rusefi.RealHwTest.main(RealHwTest.java:24)

**Comment by rusefi** [comment]
See also #441

**Comment by rusefi** [comment]
#1491 seem to have helped this.

**Comment by rusefi** [comment]
We now have reliable performance CI!

12K @ 60/2 is tested
