### ISSUE TITLE
Broadcasting from Android crashes

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1696]
@Alex Miculescu  reports a crash when "Broadcast" attempt on android 8.1.0

**Comment by rusefillc** [comment]
https://github.com/ACRA/acra seems amazing

**Comment by rusefillc** [comment]
Got the email!

```
"java.lang.IllegalStateException: CRC mismatch crc=53 vs packet=34e7f3f5 len=134 data: 
04 05 02 00 00 00 00 00 00 00 22 5C F4 CB FA 00 00 00 00 00 00 D3 FD 00 00 00 00 00 00 00 00 00 00 16 27 00 00 27 00 00 00 00 00 00 00 00 00 B0 36 00 00 00 00 00 00 00 4F 78 69 F5 F5 F3 03 64 00 95 00 64 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 52 03 B0 04 00 00 34 1D 0B 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 9A 00 00 00 36 00 00 00 6E 3D 34 01 76 3B 34 01 00 00 00 00 00 00 00 \n\t
at com.rusefi.io.tcp.BinaryProtocolServer.readPromisedBytes(BinaryProtocolServer.java:394)\n\t
at com.rusefi.io.IoStream$-CC.$default$readPacket(IoStream.java:47)\n\t
at com.rusefi.io.serial.AbstractIoStream.readPacket(Unknown Source:0)\n\t
at com.rusefi.proxy.NetworkConnector$2.handleCommand(NetworkConnector.java:146)\n\t
```

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/90344691-f5a7a480-dfe9-11ea-9461-eea25ed14d1c.png)

**Comment by rusefillc** [comment]
@shadowm60 says "please check if you can keep communication active even if screen is off, because i have a feeling communication is slow or stopped if screen is off"
