### ISSUE TITLE
Server issue maybe java 11?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1737]
Out of the blue
```
java.lang.ExceptionInInitializerError
	at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:222)
	at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:90)
	at com.rusefi.server.Backend.getControllersOnline(Backend.java:320)
	at com.rusefi.server.Backend.lambda$new$0(Backend.java:66)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:157)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:228)
	at org.takes.facets.fork.FkChain.route(FkChain.java:72)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.http.BkBasic.print(BkBasic.java:127)
	at org.takes.http.BkBasic.accept(BkBasic.java:103)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:49)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.glassfish.json.messages, locale en_US
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
	at org.glassfish.json.JsonMessages.<clinit>(JsonMessages.java:58)
	... 16 more
```

**Comment by rusefillc** [comment]
totally not java 11

that's a funny way null value is handler
