### ISSUE TITLE
HW CI repeatable error

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2224]
Happens maybe 1 in 20/30 builds but keeps happening!

```
    [junit] I 210112 144706.011 [communication executor1] MessagesCentral - postMessage EngineState: WARNING: re-adding element into event_queue
    [junit] I 210112 144716.312 [communication executor1] MessagesCentral - postMessage EngineState: WARNING: Can't connect or mount MMC/SD
    [junit] ------------- ---------------- ---------------
    [junit] 
    [junit] Testcase: testVW took 51,119 sec
    [junit] Testcase: testV12 took 91,149 sec
    [junit] 	Caused an ERROR
    [junit] rpm change did not happen: 60, actual 123.0
    [junit] java.lang.IllegalStateException: rpm change did not happen: 60, actual 123.0
    [junit] 	at com.rusefi.IoUtil.changeRpm(IoUtil.java:96)
    [junit] 	at com.rusefi.functional_tests.EcuTestHelper.assertRpmDoesNotJump(EcuTestHelper.java:43)
    [junit] 	at com.rusefi.HighRevTest.testV12(HighRevTest.java:29)
```

See #2207

**Comment by rusefillc** [comment]
replacing this one with #4772
