### ISSUE TITLE
HW CI: why does analog input test sometimes fail?

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2335]
```
    [junit] Testcase: testTpsAnalogInput took 11.466 sec
    [junit] 	FAILED
    [junit] expected:<75.0> but was:<69.64>
    [junit] junit.framework.AssertionFailedError: expected:<75.0> but was:<69.64>
    [junit] 	at com.rusefi.proteus.ProteusAnalogTest.setIdlePositionAndAssertTps(ProteusAnalogTest.java:38)
    [junit] 	at com.rusefi.proteus.ProteusAnalogTest.testTpsAnalogInput(ProteusAnalogTest.java:55)
```

what happened? It's close, but also 5.3% off.

**Comment by rusefillc** [comment]
is that the one where we had a chance recently @mck1117 ?

**Comment by mck1117** [comment]
dupe #2845
