### ISSUE TITLE
TS does not support zero length arrays?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2366]
```
camInputs4 = bits, U08, 559, [0:7], "NONE","INVALID","INVALID","INVALID","INVALID","INVALID","INVALID","INVALID","3V - CAM (A19)"
camInputsPadding = array, U08, 560, [0], 
afr_hwChannel = bits, U08, 560, [0:5], "NONE","4W - O2S (A13)","3L - IGN_7 / AFR","4B - Brake/RES1 (A7)","4AB - FTP/PPS (A18)","4V - TPS (A17)","4T - Alternator voltage (A5)","3V - CAM (A19)","4J - VTCS/AUX4 (A20)","4F - AC_PRES/AUX1 (A23)","4AA - O2S2 (A12)","4X - MAF (A9)"
```

seems to be causing
```
2/16/21 3:55:30 PM :Debug: TuneLog Editor set text
2/16/21 3:55:30 PM :Debug: Fill Constants: 91
2/16/21 3:55:30 PM :Warning: camInputsPadding array size does not match the currently loaded configuration,
	rescaled .msq values to match configuration.
java.lang.ArrayIndexOutOfBoundsException: 0
	at F.aK.a(Unknown Source)
	at F.R.a(Unknown Source)
	at V.Y.a(Unknown Source)
	at V.Y.a(Unknown Source)
	at V.Y.a(Unknown Source)
	at aI.gK.a(Unknown Source)
	at aI.g.d(Unknown Source)
	at aI.g.c(Unknown Source)
	at aI.g.g(Unknown Source)
	at aI.cH.m(Unknown Source)
	at aI.cH.b(Unknown Source)
	at aI.g.x(Unknown Source)
	at aI.cH.windowClosing(Unknown Source)
	at java.awt.Window.processWindowEvent(Window.java:2058)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2017)
	at aI.cH.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2/16/21 3:55:30 PM :Error: isDifferenceDetected:: Returning true a file is different, Error opening Saved tune:
C:\Users\user\Documents\TunerStudioProjects\h72\restorePoints\h72_2021-02-16_15.54.10.msq
2/16/21 3:55:30 PM :Info: Error: isDifferenceDetected:: Returning true a file is different, Error opening Saved tune:
```

**Comment by mck1117** [comment]
TS devs said this isn't worth it.
