### ISSUE TITLE
LOW: ArrayIndexOutOfBoundsException in console

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#316]
puff reports an ArrayIndexOutOfBoundsException

java.lang.IllegalStateException: java.lang.ArrayIndexOutOfBoundsException
        at com.rusefi.TableEditorPane.showContent(TableEditorPane.java:39)
        at com.rusefi.Launcher$5.onConnectionEstablished(Launcher.java:212)
        at com.rusefi.io.serial.PortHolder.openPort(PortHolder.java:40)
        at com.rusefi.io.serial.SerialConnector$1.run(SerialConnector.java:27)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at com.romraider.maps.Table2D.populateTable(Table2D.java:122)
        at com.romraider.maps.Rom.populateTables(Rom.java:159)
        at com.romraider.editor.ecu.ECUEditor.openImage(ECUEditor.java:189)
        at com.romraider.editor.ecu.ECUEditor.openImage(ECUEditor.java:174)
        at com.rusefi.TableEditorPane.showContent(TableEditorPane.java:37)
        ... 6 more
        
        http://rusefi.com/forum/viewtopic.php?f=5&t=373&p=20087&e=20087

Reported by: rusefi

**Comment by mck1117** [comment]
this is ancient, close?
