### ISSUE TITLE
BUG: console does not work with EAP java 9 - probably remove romraider for now?

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#319]
java.lang.IllegalAccessError: class com.romraider.util.SettingsManager (in unnamed module @0x570c7b1c) cannot access class com.sun.org.apache.xerces.internal.parsers.DOMParser (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.parsers to unnamed module @0x570c7b1c
	at com.romraider.util.SettingsManager.load(SettingsManager.java:71)
	at com.romraider.util.SettingsManager.getSettings(SettingsManager.java:51)
	at com.romraider.maps.Table.getSettings(Table.java:1086)
	at com.romraider.maps.Table.<init>(Table.java:68)
	at com.romraider.maps.Table3D.<init>(Table3D.java:70)
	at com.rusefi.ui.FuelTunePane.<init>(FuelTunePane.java:48)
	at com.rusefi.Launcher.<init>(Launcher.java:172)
	at com.rusefi.StartupFrame$3.actionPerformed(StartupFrame.java:105)
	at javax.swing.AbstractButton.fireActionPerformed(java.desktop@9-ea/AbstractButton.java:1967)
	at javax.swing.AbstractButton$Handler.actionPerformed(java.desktop@9-ea/AbstractButton.java:2308)
	at javax.swing.DefaultButtonModel.fireActionPerformed(java.desktop@9-ea/DefaultButtonModel.java:404)
	at javax.swing.DefaultButtonModel.setPressed(java.desktop@9-ea/DefaultButtonModel.java:261)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(java.desktop@9-ea/BasicButtonListener.java:269)
	at java.awt.Component.processMouseEvent(java.desktop@9-ea/Component.java:6601)
	at javax.swing.JComponent.processMouseEvent(java.desktop@9-ea/JComponent.java:3322)
	at java.awt.Component.processEvent(java.desktop@9-ea/Component.java:6366)
	at java.awt.Container.processEvent(java.desktop@9-ea/Container.java:2259)
	at java.awt.Component.dispatchEventImpl(java.desktop@9-ea/Component.java:4985)
	at java.awt.Container.dispatchEventImpl(java.desktop@9-ea/Container.java:2317)
	at java.awt.Component.dispatchEvent(java.desktop@9-ea/Component.java:4817)
	at java.awt.LightweightDispatcher.retargetMouseEvent(java.desktop@9-ea/Container.java:4896)
	at java.awt.LightweightDispatcher.processMouseEvent(java.desktop@9-ea/Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(java.desktop@9-ea/Container.java:4474)
	at java.awt.Container.dispatchEventImpl(java.desktop@9-ea/Container.java:2303)
	at java.awt.Window.dispatchEventImpl(java.desktop@9-ea/Window.java:2754)
	at java.awt.Component.dispatchEvent(java.desktop@9-ea/Component.java:4817)
	at java.awt.EventQueue.dispatchEventImpl(java.desktop@9-ea/EventQueue.java:761)
	at java.awt.EventQueue.access$500(java.desktop@9-ea/EventQueue.java:97)
	at java.awt.EventQueue$3.run(java.desktop@9-ea/EventQueue.java:712)
	at java.awt.EventQueue$3.run(java.desktop@9-ea/EventQueue.java:706)
	at java.security.AccessController.doPrivileged(java.base@9-ea/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@9-ea/ProtectionDomain.java:77)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@9-ea/ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(java.desktop@9-ea/EventQueue.java:734)
	at java.awt.EventQueue$4.run(java.desktop@9-ea/EventQueue.java:732)
	at java.security.AccessController.doPrivileged(java.base@9-ea/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@9-ea/ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(java.desktop@9-ea/EventQueue.java:731)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@9-ea/EventDispatchThread.java:199)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@9-ea/EventDispatchThread.java:124)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@9-ea/EventDispatchThread.java:113)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@9-ea/EventDispatchThread.java:109)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@9-ea/EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.run(java.desktop@9-ea/EventDispatchThread.java:90)
[/code]

Итого - не могу подключить мозги через консоль

порылся, нашёл временное решение. Этот баг только на java v9, если понизить до 8й версии - всё ок

Reported by: rusefi

**Comment by rusefillc** [comment]
@mck1117 i know you love removing stuff wanna remove RR code for now?

**Comment by mck1117** [comment]
I could be convinced to delete code :)

**Comment by mck1117** [comment]
looks like no romraider left in the repo?

![image](https://user-images.githubusercontent.com/568254/213823963-45abaf39-1c41-4020-9cb0-3a87b905d170.png)
