### ISSUE TITLE
Unable to change broken settings

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3227]
Nik has FATAL error due to VSS PAL on PA8 conflicting with joystick on something else Px8

problem is we get 

![image](https://user-images.githubusercontent.com/48498823/132144977-8318c6ce-e539-4ff5-9120-1b7e2b4649c0.png)

while trying to change settings to good ones

**Comment by rusefillc** [comment]
```
9/5/21 8:00:07 PM :Info: CrC matched skipped controller read on page:1
9/5/21 8:00:07 PM :Debug: Read All Data
9/5/21 8:00:07 PM :Debug: isBlank Time: 0 ms.
9/5/21 8:00:07 PM :Debug: DiffTime: 4 ms.
9/5/21 8:00:07 PM :Info: Difference Report disabling shared table Models
9/5/21 8:00:07 PM :Debug: Received Instruction: Retrieve Config Error, Page: 0
9/5/21 8:00:14 PM :Info: Time to save msq: 81.3948
9/5/21 8:00:14 PM :Info: dirtyData.size(): 1
9/5/21 8:00:14 PM :Debug: Received Instruction: Write Chunk, Page: 1
9/5/21 8:00:14 PM :Info: dirtyData.size(): 0
9/5/21 8:00:14 PM :Debug: Flush lasted: 213ms.
9/5/21 8:00:14 PM :Debug: Burn Page anonymous: 1
9/5/21 8:00:14 PM :Debug: Received Instruction: , Page: 1
9/5/21 8:00:14 PM :Info: Queueing burn to page:1
9/5/21 8:00:14 PM :Info: Sending, 0 bytes.
9/5/21 8:00:14 PM :Info: Loaded Restore point C:\Users\Dell2019\Documents\TunerStudioProjects\nik sept 5\CurrentTune.msq
	Sending, 0 bytes.
9/5/21 8:00:14 PM :Info: dirtyData.size(): 0
9/5/21 8:00:14 PM :Info: dirtyData.size(): 0
9/5/21 8:00:14 PM :Debug: Flush lasted: 1ms.
9/5/21 8:00:14 PM :Debug: Burn Page anonymous: -1
9/5/21 8:00:14 PM :Debug: Received Instruction: , Page: 1
9/5/21 8:00:14 PM :Info: skip burn to page:1, lastWritePage = -2
9/5/21 8:00:17 PM :Debug: burned page FAILED! 1
Sep 05, 2021 8:00:17 PM F.J d
SEVERE: null
U.b: Timeout after:3051ms. requested timeout:3050, Expected bytes:3, bytes read:0
	at y.r.a(Unknown Source)
	at F.J.b(Unknown Source)
	at F.J.a(Unknown Source)
	at F.J.d(Unknown Source)
	at F.J.c(Unknown Source)
	at F.J.y(Unknown Source)
	at y.r.c(Unknown Source)
	at y.s.run(Unknown Source)

9/5/21 8:00:17 PM :Info: Difference Report enabling shared table Models
9/5/21 8:00:17 PM :Debug: Received Instruction: Read All Tune Data, Page: 0
9/5/21 8:00:47 PM :Debug: goOffline Starting, Time:0
9/5/21 8:00:47 PM :Info: Deactivated Turbo Baud, goOffline
9/5/21 8:00:47 PM :Debug: Burn Page anonymous: -1
9/5/21 8:00:47 PM :Debug: Received Instruction: , Page: 1
9/5/21 8:00:47 PM :Info: skip burn to page:1, lastWritePage = -2
9/5/21 8:00:48 PM :Debug: goOffline about to stopProcessing, Time:251
9/5/21 8:00:48 PM :Debug: controllerOnline = 0.0
9/5/21 8:00:48 PM :Debug: cltTempWarning: Trigger Expression: coolant > 230 = 0.0
9/5/21 8:00:48 PM :Debug: goOffline Notified offline, Time:253
9/5/21 8:00:48 PM :Debug: goOffline closed port, Time:253
9/5/21 8:00:53 PM :Debug: goOffline comm thread stopped, Time:5313
9/5/21 8:00:53 PM :Debug: No Remaining Queue Write instructions
9/5/21 8:00:53 PM :Info: Difference Report enabling shared table Models
Exception in thread "MSyncReadProcess" java.lang.NullPointerException
	at aJ.gT.a(Unknown Source)
	at aJ.gT.a(Unknown Source)
	at F.an.a(Unknown Source)
	at F.an.a(Unknown Source)
	at F.ax.run(Unknown Source)
9/5/21 8:00:53 PM :Debug: goOffline Starting, Time:0
9/5/21 8:00:53 PM :Info: Deactivated Turbo Baud, goOffline
9/5/21 8:00:53 PM :Debug: goOffline about to stopProcessing, Time:1
9/5/21 8:00:53 PM :Debug: goOffline closed port, Time:1

```
