### ISSUE TITLE
BUG: all TS write fails

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#336]
Any TS write causes a delya and "burn page 0 failed" error message

Seems to happen after blockingFactor and ochBlockSize increase

in rusefi.ini file a few parameters could be tweaked:
pageActivationDelay
interWriteDelay
blockReadTimeout

![image](https://cloud.githubusercontent.com/assets/7377949/24322444/f46ae66c-113a-11e7-8b3e-84daebf88309.png)

[TunerStudioAppDebug.zip](https://github.com/rusefi/rusefi/files/870024/TunerStudioAppDebug.zip)

**Comment by rusefi** [comment]
progress: looks like a rusEfi defect, not a timing/delay issue. Note how B response is invalid

3/25/17 9:11:00 AM :Debug: Flush lasted: 0ms.
3/25/17 9:11:00 AM :Debug: Burn Page anonymous: 1
3/25/17 9:11:00 AM :Debug: Time:46.339s. Received Instruction: 
3/25/17 9:11:00 AM :Debug: CommManager got a burn for page 1, cleared lastWritePage
3/25/17 9:11:00 AM :Info: Queueing burn to page:1
3/25/17 9:11:00 AM :Time: 0:46.342: READ 3 bytes, 3 bytes
x01 x65 x00                                                           .e.

3/25/17 9:11:00 AM :Debug: old style time to read outpc: 50 ms.
3/25/17 9:11:00 AM :Debug: Time:46.344s. Processing Instruction: 
3/25/17 9:11:00 AM :Time: 0:46.343: READ 360 bytes, 360 bytes
x00 x00 x00 x00 x90 x73 x53 x42 x88 x98 x79 x42 x00 x00 x00 x00       .....sSB..yB....
x00 x00 x00 x00 x36 x27 x2A x41 x19 xFF x1B x42 xA1 x0E xC2 x40       ....6'*A...B...@
x57 x00 x00 x00 x00 x00 x00 x00 x19 xFF x1B x42 xD0 xF7 x47 x41       W..........B..GA
xCD x7F x32 x40 xCE xFC x5C x42 x9A x99 x09 x41 x00 x00 x80 x40       ..2@..\B...A...@
x00 x00 x00 x00 x00 x00 x00 x00 x8A x14 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 xC9 xA2 x33 x01 x19 xFC x19 xFC x19 xFC x19 xFC       ......3.........
x19 xFC x19 xFC x19 xFC x19 xFC x00 x00 xC0 x7F x00 x00 x00 x00       ................
xD3 xCD x3C x42 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ..<B............
x00 x00 x00 x00 x00 x00 x80 x3F x00 x00 x00 x00 x00 x00 xC0 x7F       .......?........
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x80 x3F x00 x00 x00 x00 x00 x00 x10 x42       .......?.......B
x00 x00 x60 x41 xA3 xF5 xBE x3D xB6 xA1 x86 x3F x4D xBF x3B x40       ..`A...=...?M.;@
x00 x00 x00 x00 xC4 xDE x54 x40 x00 x00 x00 x00 x00 x00 x00 x00       ......T@........
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
xA7 x00 x00 x00 x00 x00 x00 x00 x00 x00 xC0 x7F x04 x00 x00 x00       ................
x99 x17 x00 x00 xB0 xE6 x0E x42 x00 x00 x00 x00 x36 x00 x00 x00       .......B....6...
x00 x00 x00 x00 x00 x00 x00 x00 x53 xC6 x33 x01 x00 x00 x00 x00       ........S.3.....
x00 x00 xC0 x7F x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x67 xD9 xF7 x59                                       ....g..Y

3/25/17 9:11:00 AM :Time: 0:46.346: SENT 9 bytes, 9 bytes
x00 x03 x42 x00 x00 x8C x5F x80 xBC                                   ..B..._..

3/25/17 9:11:00 AM :Time: 0:46.350: READ 3 bytes, 3 bytes
x43 x41 x4E                                                           CAN

3/25/17 9:11:03 AM :Time: 0:49.350: READ Timout after 94 bytes, Expected:17220, actual read:94 Raw buffer, 94 bytes
x20 x54 x58 x20 x6F x6E x20 x50 x42 x3A x36 x0D x0A x6C x69 x6E       .TX.on.PB:6..lin
x65 x3A x31 x38 x3A x6D x73 x67 x2C x43 x41 x4E x20 x54 x58 x20       e:18:msg,CAN.TX.
x6F x6E x20 x50 x42 x36 x2C x0D x0A x43 x41 x4E x20 x52 x58 x20       on.PB6,..CAN.RX.
x6F x6E x20 x50 x42 x3A x31 x32 x0D x0A x6C x69 x6E x65 x3A x31       on.PB:12..line:1
x39 x3A x6D x73 x67 x2C x43 x41 x4E x20 x52 x58 x20 x6F x6E x20       9:msg,CAN.RX.on.
x50 x42 x31 x32 x2C x0D x0A x00 x01 x04 xD5 x6F x2B x94               PB12,......o+.

3/25/17 9:11:03 AM :Debug: burned page FAILED! 1
Mar 25, 2017 9:11:03 AM l.E d
SEVERE: null
z.b: Timeout after:3001ms. requested timeout:3000, Expected bytes:17220, bytes read:94
	at h.p.a(Unknown Source)
	at l.E.b(Unknown Source)
	at l.E.a(Unknown Source)
	at l.E.d(Unknown Source)
	at l.E.c(Unknown Source)
	at l.E.y(Unknown Source)
	at h.p.i(Unknown Source)
	at h.q.run(Unknown Source)

3/25/17 9:11:26 AM :Time: 1:12.612: SENT 13 bytes, 13 bytes
x00 x07 x6B x00 x00 x00 x00 x36 xB8 x58 x7B x6D xAA                   ..k....6.X{m.

3/25/17 9:11:26 AM :Time: 1:12.632: READ 3 bytes, 3 bytes
x00 x05 x00                                                           ...

3/25/17 9:11:26 AM :Info: CRC matches fine. 
3/25/17 9:11:26 AM :Debug:    CRC from controller page 1:xCC x68 x9A x31                                                       .h.1
3/25/17 9:11:26 AM :Time: 1:12.633: READ 8 bytes, 8 bytes
xCC x68 x9A x31 x66 x0D x5E x91                                       .h.1f.^.

3/25/17 9:11:26 AM :Debug:    Local Data CRC for page 1: xCC x68 x9A x31                                                       .h.1
3/25/17 9:11:26 AM :Debug: Time:72.633s. Processing Complete: 
3/25/17 9:11:26 AM :Debug: Real OchDelay for mar12: 50, timeout=300
3/25/17 9:11:26 AM :Time: 1:12.634: SENT 7 bytes, 7 bytes
x00 x01 x4F x34 x61 xB3 x8C                                           ..O4a..

3/25/17 9:11:26 AM :Debug: old style time to read outpc: 49 ms.
3/25/17 9:11:26 AM :Time: 1:12.683: READ 3 bytes, 3 bytes
x01 x65 x00                                                           .e.

3/25/17 9:11:26 AM :Time: 1:12.684: READ 360 bytes, 360 bytes
x00 x00 x00 x00 xB0 x29 x54 x42 x28 x0E x7A x42 x00 x00 x00 x00       .....)TB(.zB....
x00 x00 x00 x00 x36 x27 x2A x41 x28 x57 x15 x42 x16 x5F xC1 x40       ....6'*A(W.B._.@
x56 x00 x00 x00 x00 x00 x00 x00 x28 x57 x15 x42 xD6 xF8 x46 x41       V.......(W.B..FA
xC8 x79 x32 x40 xCE xA2 x5D x42 x00 x00 x08 x41 x00 x00 x80 x40       .y2@..]B...A...@
x00 x00 x00 x00 x00 x00 x00 x00 x8E x14 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 xC9 xA2 x33 x01 x19 xFC x19 xFC x19 xFC x19 xFC       ......3.........
x19 xFC x19 xFC x19 xFC x19 xFC x00 x00 xC0 x7F x00 x00 x00 x00       ................
xD3 xCD x3C x42 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ..<B............
x00 x00 x00 x00 x00 x00 x80 x3F x00 x00 x00 x00 x00 x00 xC0 x7F       .......?........
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x80 x3F x00 x00 x00 x00 x00 x00 x10 x42       .......?.......B
x00 x00 x60 x41 x33 xEF xBE x3D xC9 x7E x86 x3F x46 x88 x3B x40       ..`A3..=.~.?F.;@
x00 x00 x00 x00 x78 xBE x57 x40 x00 x00 x00 x00 x00 x00 x00 x00       ....x.W@........
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
xC1 x00 x00 x00 x00 x00 x00 x00 x00 x00 xC0 x7F x04 x00 x00 x00       ................
x99 x17 x00 x00 xB0 xE6 x0E x42 x00 x00 x00 x00 x36 x00 x00 x00       .......B....6...
x00 x00 x00 x00 x00 x00 x00 x00 x53 xC6 x33 x01 x00 x00 x00 x00       ........S.3.....
x00 x00 xC0 x7F x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x16 x1A x4A xC8                                       ......J.
