### ISSUE TITLE
TS via TCP connector and ISO-TP via PCAN

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3667]
We need PCAN ISO-TP connector in rusEFI console

related but different from #3361

**Comment by rusefillc** [comment]
current status: verifyCrcNoPending fails

![image](https://user-images.githubusercontent.com/48498823/145065283-7708a9e3-28cb-4999-9271-81709194281c.png)

```
Hello PCAN peak.can.basic.PCANBasic@63947c6b
communicationThread lookup DONE
class com.rusefi.io.CommandQueue: SerialIO started
I 211207 111232.962 [communication executor1] IsoTpConnector - -------sendBytesToCan 11 byte(s):
00 05 6B 00 00 50 5F 69 AF A0 70 
I 211207 111232.979 [communication executor1] IoStream - -------sendIsoTp 8 byte(s):
10 0B 00 05 6B 00 00 50 
I 211207 111232.979 [communication executor1] IoStream - -------sendIsoTp 6 byte(s):
21 5F 69 AF A0 70 
peak.can.basic.TPCANMsg@58116460 id=258 len=8: 30 00 00 00 00 00 00 00 0       
peak.can.basic.TPCANMsg@56d68112 id=258 len=8: 10 0B 00 05 00 2E F2 60       
peak.can.basic.TPCANMsg@52e90f10 id=258 len=8: 21 BE 79 AB 7D 82 00 00   y     
peak.can.basic.TPCANMsg@17eb8b29 id=258 len=8: 07 00 01 80 3F BA 6C AD     l 
I 211207 111232.986 [communication executor1] BinaryProtocol - rusEFI says tune CRC32 0x2ef260be 787636414

I 211207 111232.987 [communication executor1] BinaryProtocol - rusEFI says tune CRC16 0x60be 24766

E 211207 111232.987 [communication executor1] IoStream - dropPending: Unexpected pending data: 7 byte(s)
E 211207 111232.987 [communication executor1] IoStream - DROPPED FROM BUFFER: 00 01 80 3F BA 6C AD     l 
```


```
2021-12-07_11_12_33_054: EngineState: CAN_rx 100(256) 8: 10 0B 00 05 6B 00 00 50
2021-12-07_11_12_33_055: EngineState: Sending CAN message: SID 102/8 30 0 0 0 0 0 0 0
2021-12-07_11_12_33_055: EngineState: --RT: 1 00
2021-12-07_11_12_33_055: EngineState: --RT: 1 05
2021-12-07_11_12_33_056: EngineState: --RT: 1 6B
2021-12-07_11_12_33_056: EngineState: CAN_rx 100(256) 6: 21 5F 69 AF A0 70 00 00
2021-12-07_11_12_33_057: EngineState: --RT: 8 00
2021-12-07_11_12_33_057: EngineState: Sending CAN message: SID 102/8 10 B 0 5 0 2E F2 60
2021-12-07_11_12_33_058: EngineState: CAN_rx 100(256) 8: 30 00 00 00 00 00 00 00
2021-12-07_11_12_33_058: EngineState: Sending CAN message: SID 102/8 21 BE 79 AB 7D 82 0 0
2021-12-07_11_12_33_059: EngineState: --RT: 1 00
2021-12-07_11_12_33_059: EngineState: --RT: 1 00
2021-12-07_11_12_33_065: EngineState: TunerStudio: CAN invalid size: 0
2021-12-07_11_12_33_065: EngineState: CAN: ERROR: CRC header size
2021-12-07_11_12_33_065: EngineState: TunerStudio size=640 / total=6478 / errors=35 / H=4 / O=1693 / P=222 / B=0
2021-12-07_11_12_33_070: EngineState: TunerStudio W=0 / C=0 / P=0
2021-12-07_11_12_33_071: EngineState: Sending CAN message: SID 102/8 7 0 1 80 3F BA 6C AD

```

**Comment by rusefillc** [comment]
6B is TS_CRC_CHECK_COMMAND

config size is 24400 5F50

**Comment by rusefillc** [comment]
@andreika-git still same exact error with latest firmware :( 

```
2021-12-08_15_34_29_362: EngineState: --RT: 0 00
2021-12-08_15_34_29_538: EngineState: CAN_rx 100(256) 8: 10 0B 00 05 6B 00 00 50
2021-12-08_15_34_29_538: EngineState: Sending CAN message: SID 102/8 30 0 0 0 0 0 0 0
2021-12-08_15_34_29_538: EngineState: --RT: 1 00
2021-12-08_15_34_29_538: EngineState: --RT: 1 05
2021-12-08_15_34_29_539: EngineState: --RT: 1 6B
2021-12-08_15_34_29_539: EngineState: CAN_rx 100(256) 6: 21 5F 69 AF A0 70 00 00
2021-12-08_15_34_29_539: EngineState: --RT: 8 00
2021-12-08_15_34_29_540: EngineState: Sending CAN message: SID 102/8 10 B 0 5 0 2E F2 60
2021-12-08_15_34_29_540: EngineState: CAN_rx 100(256) 8: 30 00 00 00 00 00 00 00
2021-12-08_15_34_29_543: EngineState: Sending CAN message: SID 102/8 21 BE 79 AB 7D 82 0 0
2021-12-08_15_34_29_544: EngineState: --RT: 1 00
2021-12-08_15_34_29_544: EngineState: --RT: 1 00
2021-12-08_15_34_29_547: EngineState: process_ts: channel=CAN invalid size: 0
2021-12-08_15_34_29_549: EngineState: CAN: process_ts: ERROR: CRC header size
2021-12-08_15_34_29_549: EngineState: TunerStudio size=640 / total=1431 / errors=99 / H=4 / O=149 / P=193 / B=0
2021-12-08_15_34_29_551: EngineState: TunerStudio W=0 / C=0 / P=0
2021-12-08_15_34_29_551: EngineState: Sending CAN message: SID 102/8 7 0 1 80 3F BA 6C AD
2021-12-08_15_34_30_550: EngineState: --RT: 0 00
2021-12-08_15_34_31_467: EngineState: --RT: 0 00
2021-12-08_15_34_32_474: EngineState: --RT: 0 00

```

Do we have a unit test for 11 bytes payload within https://github.com/rusefi/rusefi/commit/72cefd42de8b03ff54abe77f6f404e4bd34c8724 ?

**Comment by rusefillc** [comment]
That last fix did it!!!

rusEFI console now has new "pcan_connector" argument to start PCAN bridge

![image](https://user-images.githubusercontent.com/48498823/145310027-ed74d585-f32a-4ebe-a58d-fee140a7c5d2.png)

**Comment by rusefillc** [comment]
Now that TS works via TCP connector next step is rusEFI console via PCAN

at the moment

While trying to run rusEFI console in PCAN mode

```
java.lang.IllegalStateException: ISO_TP_FRAME_CONSECUTIVE: That's an abnormal situation, and we probably should react? waitingForNumBytes=37 waitingForFrameIndex=4 frameIdx=3
	at com.rusefi.io.can.IsoTpCanDecoder.decodePacket(IsoTpCanDecoder.java:55)
	at com.rusefi.io.stream.PCanIoStream.readOnePacket(PCanIoStream.java:103)
	at com.rusefi.io.stream.PCanIoStream.lambda$setInputListener$0(PCanIoStream.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

![image](https://user-images.githubusercontent.com/48498823/145317664-491bf39f-f975-4b05-a386-1af36050879a.png)
