### ISSUE TITLE
CAN: That's an abnormal situation, and we probably should react? waitingForNumBytes=37 waitingForFrameIndex=4 frameIdx=3

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3682]
Now that TS works via TCP connector next step is rusEFI console via PCAN

at the moment

While trying to run rusEFI console in PCAN mode

```
java.lang.IllegalStateException: ISO_TP_FRAME_CONSECUTIVE: That's an abnormal situation, and we probably should react? waitingForNumBytes=37 waitingForFrameIndex=4 frameIdx=3
	at com.rusefi.io.can.IsoTpCanDecoder.decodePacket(IsoTpCanDecoder.java:55)
	at com.rusefi.io.stream.PCanIoStream.readOnePacket(PCanIoStream.java:103)
	at com.rusefi.io.stream.PCanIoStream.lambda$setInputListener$0(PCanIoStream.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

![image](https://user-images.githubusercontent.com/48498823/145317664-491bf39f-f975-4b05-a386-1af36050879a.png)

**Comment by rusefillc** [comment]
@dron0gus @mck1117 is CAN allowed to give us duplicate frames?

**Comment by rusefillc** [comment]
steps to reproduce:
add magic environment variable
RUSEFI_PCAN=true
in Windows, run rusEFI console from rusEFI bundle

expected result: happy console
actual result: unhappy console with iso-tp flow exception

**Comment by rusefillc** [comment]
not at issue any more
