### ISSUE TITLE
ETB pin not released on configuration change?

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#377]
functional tests are failing with

 [java] Waiting for 93 byte(s): text body
     [java] msg,FATAL error: PD3 req by i1 used by etb1,msg,FATAL error: PD3 req by i1 used by etb1,
     [java] postMessage EngineState: FATAL error: PD3 req by i1 used by etb1
     [java] postMessage EngineState: FATAL error: PD3 req by i1 used by etb1
     [java] Sending packet 4F
     [java] Waiting for 2 byte(s): output channels header
     [java] Waiting for 361 byte(s): output channels body
     [java] Sending packet 47
     [java] Waiting for 2 byte(s): text header
     [java] Waiting for 5 byte(s): text body

   [java] postMessage EngineState: FATAL error: PD3 req by i1 used by etb1
     [java] Sending packet 4F
     [java] Waiting for 2 byte(s): output channels header
     [java] Waiting for 361 byte(s): output channels body
     [java] Sending packet 47
     [java] Waiting for 2 byte(s): text header
     [java] Waiting for 5 byte(s): text body
     [java] Sending packet 4F
     [java] Waiting for 2 byte(s): output channels header
     [java] RPM change [200] executed in 40008
     [java] java.lang.IllegalStateException: rpm change did not happen: 200, actual 0.0
     [java]     at com.rusefi.IoUtil.changeRpm(IoUtil.java:91)
     [java]     at com.rusefi.AutoTest.testMazdaProtege(AutoTest.java:202)
     [java]     at com.rusefi.AutoTest.mainTestBody(AutoTest.java:35)
     [java]     at com.rusefi.RealHwTest.runRealHardwareTest(RealHwTest.java:59)
     [java]     at com.rusefi.RealHwTest.main(RealHwTest.java:23)

**Comment by rusefi** [comment]
S2R:

fiesta #4 config has ETB, festiva config #14 uses same pin for injection 

set engine_type 4
reboot
set engine_type 14

expexted result: no fatal error
actual result: fatal error :(
