### ISSUE TITLE
Exception in thread "PCAN reader1" java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4370]
S2R unclear, a lot of unexpected CAN traffic on the bus

https://rusefi.com/forum/viewtopic.php?p=45893#p45893

```
Exception in thread "PCAN reader1" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at peak.can.basic.TPCANMsg.setData(TPCANMsg.java:120)
        at peak.can.basic.PCANBasic.Read(Native Method)
        at com.rusefi.io.stream.PCanIoStream.readOnePacket(PCanIoStream.java:101)
        at com.rusefi.io.stream.PCanIoStream.lambda$setInputListener$0(PCanIoStream.java:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by rusefillc** [comment]
Kirby actually I know what's going on: in order to skip a packet we need to read the packet completely, in order to read the packet completely we need to allocate a buffer

looks like driver does not validate that the buffer we supply (8 bytes) is too small for whatever random weird packet you have (HUH? what kind of packets have more than 8 payload?)

**Comment by rusefillc** [comment]
Actually more update:

just pushed a questionable work-around

**Comment by rusefillc** [comment]
closing for now until reported again
