### ISSUE TITLE
github gradle to increase reliablity

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4771]
We use https://github.com/rusefi/build_support to increase performance (?) and reliability (?) of CI

Shall we place gradle-7.5.1-all.zip into https://github.com/rusefi/build_support and find the way to request that gradle wrapper downloads from github as the next step?

Specific failing build https://github.com/rusefi/rusefi/actions/runs/3448523818/jobs/5755622367

```
Downloading https://services.gradle.org/distributions/gradle-7.5.1-all.zip
............
Error: Exception in thread "main" javax.net.ssl.SSLException: Connection reset
	at sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:348)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:286)
```

**Comment by rusefillc** [comment]
@chuckwagoncomputing @ZHoob2004 anyone? :)

**Comment by rusefillc** [comment]
At the moment build is broken due to someone on the internet forgetting to update a certificate :(

maybe https://stackoverflow.com/questions/25965901/how-to-make-gradle-repository-point-to-local-directory
