### ISSUE TITLE
HW CI is not reliable enough

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4772]
Humans are fucking expensive, we commit a lot. 20 seconds waste of flaky test multiplies.

**Comment by rusefillc** [comment]
for example https://github.com/rusefi/rusefi/actions/runs/3353650060/jobs/5556605696#step:16:1340

![image](https://user-images.githubusercontent.com/48498823/201455623-09f91c28-2fd5-40ef-985c-a3c6db1b51a0.png)

**Comment by rusefillc** [comment]
@mck1117 any chance you could help?

https://github.com/rusefi/rusefi/actions/runs/3451774157/jobs/5761229627#step:16:1154

![image](https://user-images.githubusercontent.com/48498823/201486285-e6e0d150-a9bf-4305-bc0c-c04d5a356a95.png)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/actions/runs/3481584396/jobs/5822865985#step:16:1151 @mck1117

**Comment by rusefillc** [comment]
@nmschulte this one is a functional defect

not sure if proteus HW_CI setup has external wires like discovery setup has

https://github.com/rusefi/rusefi/actions/runs/3505546092/jobs/5871917337

**Comment by mck1117** [comment]
They both have external wires. The comments in the relevant Java files tell what mods are needed.

**Comment by mck1117** [comment]
Those fails all look like the same thing - comms time out, which may mean that the ECU is locked up. What's the failure rate like?

**Comment by rusefillc** [comment]
i want to say 5%-ish?

**Comment by rusefillc** [comment]
@mck1117 still 5% failure rate

https://github.com/rusefi/rusefi/actions/runs/3858743431/jobs/6577597618

**Comment by rusefillc** [comment]
@mck1117 https://github.com/rusefi/rusefi/actions/runs/3888361986/jobs/6635598767

**Comment by rusefillc** [comment]
@mck1117 https://github.com/rusefi/rusefi/actions/runs/4036174871/jobs/6938589005#step:18:726

**Comment by mck1117** [comment]
if we increase that 500ms timeout, does it get better?

**Comment by rusefillc** [comment]
@mck1117 what do we increase to 500ms exactly? Everything seems to be at least 500ms already?

![image](https://user-images.githubusercontent.com/48498823/220152827-00e9484e-427c-41b7-a9e1-3159b8f39274.png)

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/220192149-90c3251a-e49a-472a-8be9-61396f27e1c0.png)

**Comment by rusefillc** [comment]
Sorry did not read it right

**Comment by mck1117** [comment]
but it is strange because just above that it says 5000ms

**Comment by rusefillc** [comment]
@mck1117 i believe different method invocations come with different timeouts

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/actions/runs/11978464036

```
2024-11-22_14_03_18_263<EOT>: Sleeping 5 seconds
I 241122 140318.265 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Emulating position sensor(s). RPM=6000
I 241122 140318.265 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: confirmation_rpm 6000:8
2024-11-22_14_03_23_264<EOT>: Sleeping 40 seconds
I 241122 140403.264 [main] IoUtil - Sending command [threadsinfo]
I 241122 140403.264 [ECU Commands Queue] BinaryProtocol - Sending [threadsinfo]
I 241122 140403.346 [ECU Commands Queue] IoUtil - Got confirmation in 82ms
I 241122 140403.346 [main] IoUtil - Command [threadsinfo] executed in 82
Ran 22 tests total.
Ignored 0 tests.
Failed 1 tests.
testV12(com.rusefi.f4discovery.HighRevTest): Failed Got 3998.0 while trying to stay at 6000 after 3 seconds
java.lang.IllegalStateException: Failed Got 3998.0 while trying to stay at 6000 after 3 seconds
Test failed: testV12(com.rusefi.f4discovery.HighRevTest) because Failed Got 3998.0 while trying to stay at 6000 after 3 seconds
Exception:
	at com.rusefi.functional_tests.EcuTestHelper.lambda$static$0(EcuTestHelper.java:28)
	at com.rusefi.functional_tests.EcuTestHelper.assertRpmDoesNotJump(EcuTestHelper.java:57)
	at com.rusefi.f4discovery.HighRevTest.runHighRevTest(HighRevTest.java:31)
	at com.rusefi.f4discovery.HighRevTest.testV12(HighRevTest.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
	at com.rusefi.CmdJUnitRunner.runHardwareTest(CmdJUnitRunner.java:26)
	at com.rusefi.CmdJUnitRunner.runHardwareTestAndExit(CmdJUnitRunner.java:10)
	at com.rusefi.HwCiF4Discovery.main(HwCiF4Discovery.java:40)
Have we left any non-daemon threads?
Name            	 State           	 Priority        	 isDaemon
Common-Cleaner  	 TIMED_WAITING   	 8               	 true
Finalizer       	 WAITING         	 8               	 true
main            	 RUNNABLE        	 5               	 false
ECU Commands Queue 	 WAITING         	 5               	 true
```
