### ISSUE TITLE
HW CI instability: handleShaftSignal unexpected loop

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5661]
handleShaftSignal unexpected loop

```
 231029 165633.791 [main] IoUtil - Sending command [set engine_type 3]
I 231029 165633.792 [ECU Commands Queue] BinaryProtocol - Sending [set engine_type 3]
I 231029 165636.120 [ECU Commands Queue] IoUtil - Got confirmation in 2328ms
I 231029 165636.120 [main] IoUtil - Command [set engine_type 3] executed in 2329
2023-10-29_16_56_36_121<EOT>: Sleeping 1 seconds
I 231029 165636.127 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: applyNonPersistentConfiguration()
I 231029 165636.128 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: initializeTriggerWaveform(TT_FORD_ASPIRE/1)
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Writing pending configuration...
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: FLASH_SUCCESS
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: PC4
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: PA3
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: PA6
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: PA5
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: NONE
I 231029 165636.129 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: unregistering PC15
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: PC15
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: unregistering PE6
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUnused: PE6
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUsed: Tps1Primary on PA3
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUsed: BatteryVoltage on PA0
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUsed: Clt on PC1
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUsed: AFR on PC4
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: extiTriggerTurnOnInputPin Trigger #1 PC6
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUsed: Trigger #1 on PC6
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: extiTriggerTurnOnInputPin Trigger #2 PA5
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUsed: Trigger #2 on PA5
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: pin_markUsed: trigger debug on PC15
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: AUX Serial started
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: initializeTriggerWaveform(TT_FORD_ASPIRE/1)
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Template FORD_ASPIRE_1996/3 trigger TT_FORD_ASPIRE/LM_SPEED_DENSITY/0
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: configurationVersion=18
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: rpmHardLimit: 7000/operationMode=2
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: globalTriggerAngleOffset=175.00
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: === cranking ===
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: crankingRpm: 550
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: cranking injection IM_SIMULTANEOUS
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: cranking timing -37.00
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: === ignition ===
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: ignitionMode: IM_ONE_COIL/enabled=Yes
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: timingMode: TM_DYNAMIC
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: === injection ===
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: injection IM_SEQUENTIAL enabled=Yes
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: injectionPins: mode OM_DEFAULT
I 231029 165636.130 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: injection #1 @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: injection #2 @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: injection #3 @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: injection #4 @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: ignitionPins: mode OM_DEFAULT
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: ignition #1 @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: ignition #2 @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: ignition #3 @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: ignition #4 @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: idlePin: mode OM_DEFAULT @ NONE freq=200
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: malfunctionIndicator: NONE mode=OM_DEFAULT
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: fuelPumpPin: mode OM_DEFAULT @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: fanPin: mode OM_DEFAULT @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: mainRelay: mode OM_DEFAULT @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: starterRelay: mode OM_DEFAULT @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: alternator field: mode OM_DEFAULT @ NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: map_avg=Yes/wa=Yes
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: isManualSpinningMode=No/isCylinderCleanupEnabled=Yes
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: clutchUp@NONE: No
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: clutchDown@NONE: Yes
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: digitalPotentiometerSpiDevice 0
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: digitalPotentiometer CS0 PD7
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: digitalPotentiometer CS1 NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: digitalPotentiometer CS2 PD5
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: digitalPotentiometer CS3 NONE
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: spi 1=No/2=No/3=Yes/4=No
I 231029 165636.131 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: confirmation_set engine_type 3:17
I 231029 165636.180 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: setTpsAccelLen: Length should be positive [0]
I 231029 165637.121 [main] IoUtil - Sending command [enable pwm]
I 231029 165637.122 [ECU Commands Queue] BinaryProtocol - Sending [enable pwm]
I 231029 165637.210 [ECU Commands Queue] IoUtil - Got confirmation in 89ms
I 231029 165637.210 [main] IoUtil - Command [enable pwm] executed in 89
I 231029 165637.210 [main] IoUtil - Sending command [enable self_stimulation]
I 231029 165637.211 [ECU Commands Queue] BinaryProtocol - Sending [enable self_stimulation]
I 231029 165637.216 [ECU Commands Queue] IoUtil - Got confirmation in 6ms
I 231029 165637.216 [main] IoUtil - Command [enable self_stimulation] executed in 6
I 231029 165637.216 [main] IoUtil - Sending command [disable cylinder_cleanup]
I 231029 165637.217 [ECU Commands Queue] BinaryProtocol - Sending [disable cylinder_cleanup]
I 231029 165637.218 [ECU Commands Queue] IoUtil - Got confirmation in 2ms
I 231029 165637.218 [main] IoUtil - Command [disable cylinder_cleanup] executed in 2
I 231029 165637.219 [main] IoUtil - Sending command [set_sensor_mock 4 69.12]
I 231029 165637.219 [ECU Commands Queue] BinaryProtocol - Sending [set_sensor_mock 4 69.12]
I 231029 165637.220 [ECU Commands Queue] IoUtil - Got confirmation in 1ms
I 231029 165637.220 [main] IoUtil - Command [set_sensor_mock 4 69.12] executed in 1
I 231029 165637.221 [main] IoUtil - Sending command [set_sensor_mock 30 12]
I 231029 165637.221 [ECU Commands Queue] BinaryProtocol - Sending [set_sensor_mock 30 12]
I 231029 165637.222 [ECU Commands Queue] IoUtil - Got confirmation in 1ms
I 231029 165637.222 [main] IoUtil - Command [set_sensor_mock 30 12] executed in 1
I 231029 165637.222 [main] IoUtil - Sending command [set cranking_rpm 500]
I 231029 165637.222 [ECU Commands Queue] BinaryProtocol - Sending [set cranking_rpm 500]
I 231029 165637.225 [ECU Commands Queue] IoUtil - Got confirmation in 3ms
I 231029 165637.225 [main] IoUtil - Command [set cranking_rpm 500] executed in 3
I 231029 165637.225 [main] IoUtil - AUTOTEST rpm EN 200
I 231029 165637.225 [main] IoUtil - Sending command [rpm 200]
I 231029 165637.226 [ECU Commands Queue] BinaryProtocol - Sending [rpm 200]
I 231029 165637.227 [ECU Commands Queue] IoUtil - Got confirmation in 2ms
I 231029 165637.227 [main] IoUtil - Command [rpm 200] executed in 2
I 231029 165637.285 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: [pwm] enabled
I 231029 165637.286 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: confirmation_enable pwm:10


I 231029 165713.328 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: confirmation_set_individual_coils_ignition:29
I 231029 165713.328 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: confirmation_reset_engine_chart:18
I 231029 165713.328 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: setTpsAccelLen: Length should be positive [0]
I 231029 165713.328 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: CRITICAL error: handleShaftSignal unexpected loop end 20231029@stm32f407vg
```

**Comment by rusefillc** [comment]
No, still an issue

```
	at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
	at com.rusefi.CmdJUnitRunner.runHardwareTest(CmdJUnitRunner.java:26)
	at com.rusefi.CmdJUnitRunner.runHardwareTestAndExit(CmdJUnitRunner.java:10)
	at com.rusefi.HwCiF4Discovery.main(HwCiF4Discovery.java:40)
test(com.rusefi.f4discovery.VssHardwareLoopTest): Not true: Fatal not expected: CRITICAL error: handleShaftSignal unexpected loop end 20240421@community
Test failed: test(com.rusefi.f4discovery.VssHardwareLoopTest) because Not true: Fatal not expected: CRITICAL error: handleShaftSignal unexpected loop end 20240421@community
Exception:
testV12(com.rusefi.f4discovery.HighRevTest): Not true: Fatal not expected: CRITICAL error: handleShaftSignal unexpected loop end 20240421@community
Test failed: testV12(com.rusefi.f4discovery.HighRevTest) because Not true: Fatal not expected: CRITICAL error: handleShaftSignal unexpected loop end 20240421@community
Exception:
testVW(com.rusefi.f4discovery.HighRevTest): Not true: Fatal not expected: CRITICAL error: handleShaftSignal unexpected loop end 20240421@community
Test failed: testVW(com.rusefi.f4discovery.HighRevTest) because Not true: Fatal not expected: CRITICAL error: handleShaftSignal unexpected loop end 20240421@community
```

**Comment by rusefillc** [comment]
problem: we do not have S2R

@kifir23917 let's add some assertions and wait for next occurrence? :(

**Comment by rusefillc** [comment]
HwCiF4Discovery.java

**Comment by rusefillc** [comment]
```
java.lang.AssertionError: Not true: Fatal not expected: CRITICAL error: handleShaftSignal unexpected loop end 2 10 545.000000000 20240511@community
	at org.junit.Assert.fail(Assert.java:89)
	at com.rusefi.TestingUtils.assertTrue(TestingUtils.java:34)
	at com.rusefi.TestingUtils.assertNull(TestingUtils.java:104)
	at com.rusefi.functional_tests.TestHelper.assertNotFatal(TestHelper.java:21)
	at com.rusefi.functional_tests.EcuTestHelper.sendCommand(EcuTestHelper.java:99)
	at com.rusefi.functional_tests.EcuTestHelper.sendCommand(EcuTestHelper.java:95)
	at com.rusefi.functional_tests.EcuTestHelper.createInstance(EcuTestHelper.java:86)
	at com.rusefi.RusefiTestBase.startUp(RusefiTestBase.java:17)
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
```

**Comment by kifir23917** [comment]
By the moment we meet this issue only `During start-up`:
- https://github.com/rusefi/rusefi/actions/runs/9099107159/job/25010894605?pr=6518

**Comment by rusefillc** [comment]
it's annoying and it keeps happening :(

```
Caused by: java.lang.AssertionError: Not true: Fatal not expected: CRITICAL error: handleShaftSignal unexpected loop end 2 10 545.000000000 545.000000000 20250617@community
	at org.junit.Assert.fail(Assert.java:89)
	at com.rusefi.TestingUtils.assertTrue(TestingUtils.java:34)
	at com.rusefi.TestingUtils.assertNull(TestingUtils.java:104)
	at com.rusefi.functional_tests.TestHelper.assertNotFatal(TestHelper.java:21)
	at com.rusefi.functional_tests.EcuTestHelper.sendCommand(EcuTestHelper.java:99)
	at com.rusefi.functional_tests.EcuTestHelper.sendCommand(EcuTestHelper.java:95)
	at com.rusefi.functional_tests.EcuTestHelper.createInstance(EcuTestHelper.java:88)
	at com.rusefi.RusefiTestBase.startUp(RusefiTestBase.java:21)
	... 37 more
```

@awpe any chance you can perform a miracle here?
