### ISSUE TITLE
simulatorFunctionalTestLauncherWithSimulator fails locally

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5669]
running simulatorFunctionalTestLauncherWithSimulator locally fails

```
from console: efiPrintfInternal:msg`Stimulator: updating trigger shape for ch0: 1/0 5`
from console: 
from console: ERROR creating file: [generated/simulator_tune_image.bin]
from console: Please check folder exists and is writeable.efiPrintfInternal:msg`Emulating position sensor(s). RPM=1200`
from console: 
from console: Full Duplex Channel SD1 listening on port 29001
from console: Full Duplex Channel SD2 listening on port 29002
from console: efiPrintfInternal:msg`setTpsAccelLen: Length should be positive [0]`
from console: 
from console: efiPrintfInternal:msg`LUA loading script length: 572...`
from console: 
from console: efiPrintfInternal:msg`LUA script loaded successfully!`
from console: 
from console: efiPrintfInternal:msg`WARNING: out-of-order coil off Coil 1`
from console: 
from console: efiPrintfInternal:msg`Skipped zero-duration priming pulse.`
from console: 
I 231031 115809.060 [main] LinkManager - LinkManager: Starting 29001
I 231031 115809.067 [main] StreamConnector - StreamConnector: connecting
I 231031 115809.067 [main] StreamConnector - scheduleOpening
I 231031 115809.067 [ECU Communication Executor1] StreamConnector - scheduleOpening>openPort
I 231031 115809.068 [ECU Communication Executor1] LinkManager - class com.rusefi.io.LinkManager$4: Opening TCP port: 29001
from console: Init: connection on SD1
I 231031 115809.095 [[start] TCP reader1] ByteReader - [start] Running TCP connection loop
I 231031 115809.115 [ECU Communication Executor1] BinaryProtocol - Got rusEFI master.2023.10.31.f407-discovery.3219724185  signature
I 231031 115810.498 [ECU Communication Executor1] BinaryProtocol - current_configuration.rusefi_binary Local cache CRC 8ea88f6d

I 231031 115810.498 [ECU Communication Executor1] BinaryProtocol - rusEFI says tune CRC32 0xb041663d -1337891267

I 231031 115810.498 [ECU Communication Executor1] BinaryProtocol - rusEFI says tune CRC16 0x663d 26173

I 231031 115810.498 [ECU Communication Executor1] BinaryProtocol - Reading from controller...
Saving 23880 bytes of configuration into current_configuration.rusefi_binarySaved to current_configuration.rusefi_binary
I 231031 115810.926 [ECU Communication Executor1] IniFileModel - Searching for rusefi*.ini in ..
E 231031 115810.927 [ECU Communication Executor1] IniFileModel - No such file: null
Ignoring java.lang.IllegalStateException: Empty Msq file
I 231031 115810.934 [ECU Communication Executor1] BinaryProtocol - Got configuration from controller 23880 byte(s)
2023-10-31_11_58_10_961<EOT>: Got first signal in 1893ms
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 6`
from console: 
I 231031 115811.182 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: *** rusEFI LLC (c) 2012-2023. All rights reserved.
I 231031 115811.269 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: *** rusEFI v20231031@simulator
I 231031 115811.269 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: *** Chibios Kernel:       6.1.4
I 231031 115811.269 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: *** Compiled:     Oct 31 2023 - 11:10:16
I 231031 115811.269 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: *** COMPILER=11.4.0
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: hellenBoardId=0
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: CH_CFG_ST_FREQUENCY=100000
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: PORT_IDLE_THREAD_STACK_SIZE=256
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: CH_DBG_ENABLE_ASSERTS=1
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: CH_DBG_SYSTEM_STATE_CHECK=1
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: CH_DBG_ENABLE_STACK_CHECK=0
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: EFI_LOGIC_ANALYZER=0
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: EFI_TUNER_STUDIO=1
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: EFI_SIGNAL_EXECUTOR_SLEEP=1
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: EFI_SHAFT_POSITION_INPUT=1
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: EFI_INTERNAL_ADC=0
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: readFromFlash 1
I 231031 115811.270 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Reading second configuration copy
I 231031 115811.271 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: readFromFlash 2
I 231031 115811.271 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: setTpsAccelLen: Length should be positive [0]
I 231031 115811.271 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: engine sniffer: No
I 231031 115811.271 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: engine sniffer size=400
I 231031 115811.272 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: initHardware() OK!
I 231031 115811.272 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Emulating MINIMAL_PINS
I 231031 115811.272 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Emulating position sensor(s). RPM=1200
I 231031 115811.272 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Stimulator: updating trigger shape for ch0: 1/0 5
I 231031 115811.272 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Emulating position sensor(s). RPM=1200
I 231031 115811.272 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: setTpsAccelLen: Length should be positive [0]
I 231031 115811.272 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: LUA loading script length: 572...
I 231031 115811.272 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: LUA script loaded successfully!
I 231031 115811.272 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: WARNING: out-of-order coil off Coil 1
I 231031 115811.273 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Skipped zero-duration priming pulse.
Got 38 packets
Got 0 packets
Got 1 packets
from console: efiPrintfInternal:msg`Running bench: ON_TIME=1000000 us OFF_TIME=100000 us Counter=2`
from console: 
from console: efiPrintfInternal:msg`output on N/A`
from console: 
Got 0 packets
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 7`
from console: 
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 9`
from console: 
from console: efiPrintfInternal:msg`Done!`
from console: 
I 231031 115813.681 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Done!
Got 1 packets
Got 0 packets
Got 1 packets
from console: efiPrintfInternal:msg`Running bench: ON_TIME=3000000 us OFF_TIME=100000 us Counter=2`
from console: 
from console: efiPrintfInternal:msg`output on N/A`
from console: 
Got 0 packets
I 231031 115814.151 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Running bench: ON_TIME=3000000 us OFF_TIME=100000 us Counter=2
I 231031 115814.151 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: output on N/A
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 10`
from console: 
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 11`
from console: 
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 12`
from console: 
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 13`
from console: 
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 14`
from console: 
Writing 12250 event(s)
using long deltas for ch #0
using long deltas for ch #2
using long deltas for ch #3
using long deltas for ch #4
writeFooter logs/rusEFI_trigger_log_2023-10-31_11_58_10_990.logicdata
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 15`
from console: 
from console: efiPrintfInternal:msg`Done!`
from console: 
I 231031 115820.350 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Done!
Got 1 packets
Got 0 packets
Got 1 packets
from console: efiPrintfInternal:msg`Running bench: ON_TIME=2000000 us OFF_TIME=100000 us Counter=2`
from console: 
from console: efiPrintfInternal:msg`output on N/A`
from console: 
Got 0 packets
I 231031 115820.746 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Running bench: ON_TIME=2000000 us OFF_TIME=100000 us Counter=2
I 231031 115820.746 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: output on N/A
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 16`
from console: 
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 18`
from console: 
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 19`
from console: 
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 20`
from console: 
from console: efiPrintfInternal:msg`Done!`
from console: 
I 231031 115824.912 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Done!
Got 1 packets
Got 0 packets
Got 1 packets
from console: efiPrintfInternal:msg`Running bench: ON_TIME=800000 us OFF_TIME=100000 us Counter=2`
from console: 
from console: efiPrintfInternal:msg`output on N/A`
from console: 
Got 0 packets
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 21`
from console: 
I 231031 115825.400 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Running bench: ON_TIME=800000 us OFF_TIME=100000 us Counter=2
I 231031 115825.400 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: output on N/A
from console: efiPrintfInternal:rusEfiVersion`20231031@simulator simulator MINIMAL_PINS 22`
from console: 
Got 1 packets
java.lang.IllegalStateException: BENCH_AC_COMPRESSOR_RELAY: Unexpected pin state duration: [0]=100 [1]=2000 toggleTimeMs=800
	at com.rusefi.simulator.SimulatorFunctionalTest.testOutputPin(SimulatorFunctionalTest.java:208)
	at com.rusefi.simulator.SimulatorFunctionalTest.mainTestBody(SimulatorFunctionalTest.java:37)
	at com.rusefi.SimulatorFunctionalTestLauncher.main(SimulatorFunctionalTestLauncher.java:27)
2023-10-31_11_58_27_494<EOT>: Destroying sub-process...
E 231031 115827.497 [[start] TCP reader1] ByteReader - TcpIoStream: End of connection java.net.SocketException: Connection reset
2023-10-31_11_58_27_497<EOT>: exitValue: 1
end of console
SystemOut Hook done for rusefi_tool.log

> Task :autotest:simulatorFunctionalTestLauncherWithSimulator FAILED

```

**Comment by rusefillc** [comment]
Weird thing: fails on windows 11, does not fail on linux :(

**Comment by rusefillc** [comment]
same PC fails using official simulator binary from bundle (note that bundle simulator compiles without debug)

```
I 231101 132507.954 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Engine runs we can disengage the starter
I 231101 132508.340 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Engine runs we can disengage the starter
I 231101 132508.340 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Engine runs we can disengage the starter
I 231101 132508.340 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Engine runs we can disengage the starter
I 231101 132508.340 [ECU Communication Executor1] MessagesCentral - postMessage EngineState: Engine runs we can disengage the starter
java.lang.IllegalStateException: BENCH_STARTER_ENABLE_RELAY: Unexpected pin state duration: [0]=100 [1]=800 toggleTimeMs=4000
	at com.rusefi.simulator.SimulatorFunctionalTest.testOutputPin(SimulatorFunctionalTest.java:214)
	at com.rusefi.simulator.SimulatorFunctionalTest.mainTestBody(SimulatorFunctionalTest.java:44)
	at com.rusefi.SimulatorFunctionalTestLauncher.main(SimulatorFunctionalTestLauncher.java:27)
SystemOut Hook done for rusefi_tool.log

> Task :autotest:simulatorFunctionalTestLauncherAssumungSimulatorWasStartedExternally FAILED
```
