### ISSUE TITLE
autoupdate fails - classloader right after file overwrite

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6777]
we crash

```
E 240807 121255.641 [main] Autoupdate - Failed to start
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.rusefi.autoupdate.Autoupdate.startConsole(Autoupdate.java:106)
	at com.rusefi.autoupdate.Autoupdate.autoupdate(Autoupdate.java:85)
	at com.rusefi.autoupdate.Autoupdate.main(Autoupdate.java:42)
Caused by: java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at com.rusefi.ConsoleUI.startUi(ConsoleUI.java:204)
	at com.rusefi.Launcher.main(Launcher.java:44)
	... 7 more
Caused by: java.lang.IllegalStateException: java.lang.RuntimeException: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at com.rusefi.ConsoleUI.awtCode(ConsoleUI.java:249)
	at com.rusefi.ConsoleUI.lambda$startUi$2(ConsoleUI.java:204)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at com.rusefi.core.net.ConnectionAndMeta.getProperties(ConnectionAndMeta.java:75)
	at com.rusefi.core.net.ConnectionAndMeta.getBoolead(ConnectionAndMeta.java:63)
	at com.rusefi.core.net.ConnectionAndMeta.useSimulator(ConnectionAndMeta.java:54)
	at com.rusefi.StartupFrame.showUi(StartupFrame.java:138)
	at com.rusefi.ConsoleUI.awtCode(ConsoleUI.java:245)
	... 14 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1023)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1033)
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:483)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at java.base/java.util.Properties$LineReader.readLine(Properties.java:502)
	at java.base/java.util.Properties.load0(Properties.java:418)
	at java.base/java.util.Properties.load(Properties.java:407)
	at com.rusefi.core.net.ConnectionAndMeta.getProperties(ConnectionAndMeta.java:72)
	... 18 more
```

**Comment by rusefillc** [comment]
Do we crash every time new file is downloaded? Is this because .jar is overwritten?

**Comment by rusefillc** [comment]
fixed with a hack :(

**Comment by rusefillc** [comment]
![image](https://github.com/user-attachments/assets/a49afb4b-b09c-4bd4-9c55-d01cd41ebbe2)

**Comment by rusefillc** [comment]
Looks like still an issue :(

```
I 240823 145946.960 [main] Launcher - rusEFI UI console 20240823
I 240823 145946.960 [main] Launcher - Compiled Fri Aug 23 14:59:46 EDT 2024
I 240823 145946.960 [main] Launcher - 


E 240823 145947.002 [main] Autoupdate - Failed to start
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.rusefi.autoupdate.Autoupdate.startConsole(Autoupdate.java:205)
	at com.rusefi.autoupdate.Autoupdate.autoupdate(Autoupdate.java:91)
	at com.rusefi.autoupdate.Autoupdate.main(Autoupdate.java:58)
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at com.rusefi.core.net.ConnectionAndMeta.getProperties(ConnectionAndMeta.java:106)
	at com.rusefi.ui.basic.BasicStartupFrame.<init>(BasicStartupFrame.java:59)
	at com.rusefi.ui.basic.BasicStartupFrame.runTool(BasicStartupFrame.java:55)
	at com.rusefi.tools.ConsoleTools.runTool(ConsoleTools.java:328)
	at com.rusefi.Launcher.main(Launcher.java:41)
	... 7 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1023)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1033)
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:483)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at java.base/java.util.Properties$LineReader.readLine(Properties.java:502)
	at java.base/java.util.Properties.load0(Properties.java:418)
	at java.base/java.util.Properties.load(Properties.java:407)
	at com.rusefi.core.net.ConnectionAndMeta.getProperties(ConnectionAndMeta.java:103)
	... 11 more
E 240823 145947.004 [main] Autoupdate - Autoupdate Error
java.lang.IllegalStateException: Invoking console: java.lang.reflect.InvocationTargetException
	at com.rusefi.autoupdate.Autoupdate.startConsole(Autoupdate.java:209)
	at com.rusefi.autoupdate.Autoupdate.autoupdate(Autoupdate.java:91)
	at com.rusefi.autoupdate.Autoupdate.main(Autoupdate.java:58)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.rusefi.autoupdate.Autoupdate.startConsole(Autoupdate.java:205)
	... 2 more
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at com.rusefi.core.net.ConnectionAndMeta.getProperties(ConnectionAndMeta.java:106)
	at com.rusefi.ui.basic.BasicStartupFrame.<init>(BasicStartupFrame.java:59)
	at com.rusefi.ui.basic.BasicStartupFrame.runTool(BasicStartupFrame.java:55)
	at com.rusefi.tools.ConsoleTools.runTool(ConsoleTools.java:328)
	at com.rusefi.Launcher.main(Launcher.java:41)
	... 7 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1023)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1033)
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:483)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at java.base/java.util.Properties$LineReader.readLine(Properties.java:502)
	at java.base/java.util.Properties.load0(Properties.java:418)
	at java.base/java.util.Properties.load(Properties.java:407)
	at com.rusefi.core.net.ConnectionAndMeta.getProperties(ConnectionAndMeta.java:103)
	... 11 more

```
