### ISSUE TITLE
Console is broken on Windows 11

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6821]
![image](https://github.com/user-attachments/assets/acdb190d-86eb-4cba-9e06-788a15a39234)

java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at com.rusefi.ConsoleUI.startUi(ConsoleUI.java:204)
	at com.rusefi.Launcher.main(Launcher.java:47)
Caused by: java.lang.IllegalStateException: java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
	at com.rusefi.ConsoleUI.awtCode(ConsoleUI.java:249)
	at com.rusefi.ConsoleUI.lambda$startUi$2(ConsoleUI.java:204)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at com.rusefi.ui.util.URLLabel.createUri(URLLabel.java:29)
	at com.rusefi.ui.util.URLLabel.<init>(URLLabel.java:23)
	at com.rusefi.maintenance.ProgramSelector.createHelpButton(ProgramSelector.java:348)
	at com.rusefi.StartupFrame.showUi(StartupFrame.java:166)
	at com.rusefi.ConsoleUI.awtCode(ConsoleUI.java:245)
	... 14 more

**Comment by ElDominio** [comment]
20240808 launches, 20240809 crashes
