### ISSUE TITLE
console openblt broken under linux 

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6957]
```
java.lang.NoClassDefFoundError: Could not initialize class com.rusefi.maintenance.OpenbltJni
	at com.rusefi.maintenance.ProgramSelector.flashOpenbltSerialJni(ProgramSelector.java:314)
	at com.rusefi.maintenance.ProgramSelector.flashOpenbltSerialAutomatic(ProgramSelector.java:258)
	at com.rusefi.maintenance.jobs.OpenBltAutoJob.doJob(OpenBltAutoJob.java:16)
	at com.rusefi.maintenance.jobs.AsyncJobExecutor.lambda$executeJob$0(AsyncJobExecutor.java:15)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no openblt_jni in java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib [in thread "mx"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at com.rusefi.maintenance.OpenbltJni.<clinit>(OpenbltJni.java:47)
	at com.rusefi.maintenance.ProgramSelector.flashOpenbltSerialJni(ProgramSelector.java:306)
	... 4 more
```

**Comment by rusefillc** [comment]
``java -Djava.library.path=. -jar rusefi_console.jar``

```
java.lang.NoClassDefFoundError: Could not initialize class com.rusefi.maintenance.OpenbltJni
	at com.rusefi.maintenance.ProgramSelector.flashOpenbltSerialJni(ProgramSelector.java:314)
	at com.rusefi.maintenance.jobs.OpenBltManualJob.doJob(OpenBltManualJob.java:16)
	at com.rusefi.maintenance.jobs.AsyncJobExecutor.lambda$executeJob$0(AsyncJobExecutor.java:15)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /home/Andrey/Downloads/rusefi.snapshot.uaefi/console/libopenblt_jni.so: libopenblt.so: cannot open shared object file: No such file or directory [in thread "mx"]
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at com.rusefi.maintenance.OpenbltJni.<clinit>(OpenbltJni.java:47)
	at com.rusefi.maintenance.ProgramSelector.flashOpenbltSerialJni(ProgramSelector.java:306)
	... 3 more
```

**Comment by rusefillc** [comment]
export LD_LIBRARY_PATH=.  ; java -Djava.library.path=. -jar rusefi_console.jar

```
java.lang.NoClassDefFoundError: Could not initialize class com.rusefi.maintenance.OpenbltJni
	at com.rusefi.maintenance.ProgramSelector.flashOpenbltSerialJni(ProgramSelector.java:314)
	at com.rusefi.maintenance.jobs.OpenBltManualJob.doJob(OpenBltManualJob.java:16)
	at com.rusefi.maintenance.jobs.AsyncJobExecutor.lambda$executeJob$0(AsyncJobExecutor.java:15)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /home/Andrey/Downloads/rusefi.snapshot.uaefi/console/libopenblt_jni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./libopenblt.so) [in thread "mx"]
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at com.rusefi.maintenance.OpenbltJni.<clinit>(OpenbltJni.java:47)
	at com.rusefi.maintenance.ProgramSelector.flashOpenbltSerialJni(ProgramSelector.java:306)
	... 3 more
```

**Comment by rusefillc** [comment]
https://github.com/realm/realm-js/pull/6094

**Comment by rusefillc** [comment]
upgrading my linux has helped https://mxlinux.org/wiki/system/upgrading-from-mx-21-to-mx-23-without-reinstalling/

looks like root cause - we depend on too new of a lib version, ideally we should depend on an older one?

**Comment by rusefillc** [comment]
Next step official console.sh?
