### ISSUE TITLE
integration testing on new build server is unreliable - disconnects

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#816]
this is flashing to real stm32f407 discovery hardware and testing via microUSB on ST virtual serial port

Both W7
Both 2017q4 gcc
Already tried moving stm32f407 devices around - it's not specific to stm32f407 device or cables

On new build server running same W7 real hardware integration testing is not reliable - serial connectivity between java testing suite and real hardware is lost randomly during a test

```
 [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: text header: waiting for 2 byte(s)
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: IncomingDataBuffer: 347 byte(s) arrived
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: text body: waiting for 345 byte(s)
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: time,161.360,rpm,0,CLT,79.93,TPS,0.00,IAT,30.00,VBatt,5.33,MAP,0.00,time,161.561,rpm,0,CLT,78.14,TPS,0.00,IAT,30.00,VBatt,5.33,MAP,0.00,time,161.761,rpm,0,CLT,77.77,TPS,0.00,IAT,30.00,VBatt,5.33,MAP,0.00,time,161.960,rpm,0,CLT,77.65,TPS,0.00,IAT,30.00,VBatt,5.33,MAP,0.00,time,162.160,rpm,0,CLT,79.67,TPS,0.00,IAT,30.00,VBatt,5.33,MAP,0.00,
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: Sending packet 4F 00 00 64 01 
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: output channels header: waiting for 2 byte(s)
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: IncomingDataBuffer: 363 byte(s) arrived
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: output channels body: waiting for 361 byte(s)
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: Sending packet 47 
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: text header: waiting for 2 byte(s)
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: IncomingDataBuffer: 7 byte(s) arrived
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: text body: waiting for 5 byte(s)
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: Sending packet 4F 00 00 64 01 
     [java] Sat Jun 01 22:03:28 EDT 2019<EOT>: output channels header: waiting for 2 byte(s)
     [java] Sat Jun 01 22:03:33 EDT 2019<EOT>: output channels header: timeout. Got only 0
     [java] Sat Jun 01 22:03:33 EDT 2019<EOT>: Sending packet 47 
     [java] Sat Jun 01 22:03:33 EDT 2019<EOT>: text header: waiting for 2 byte(s)
     [java] Sat Jun 01 22:03:37 EDT 2019<EOT>: Sending command [enable self_stimulation]
     [java] Sat Jun 01 22:03:37 EDT 2019<EOT>: Sending [enable self_stimulation]
     [java] Sat Jun 01 22:03:38 EDT 2019<EOT>: text header: timeout. Got only 0
     [java] Sat Jun 01 22:03:38 EDT 2019<EOT>: Sending packet 4F 00 00 64 01 
     [java] Sat Jun 01 22:03:38 EDT 2019<EOT>: output channels header: waiting for 2 byte(s)
     [java] Sat Jun 01 22:03:43 EDT 2019<EOT>: output channels header: timeout. Got only 0
     [java] Sat Jun 01 22:03:43 EDT 2019<EOT>: Sending packet 47 
     [java] Sat Jun 01 22:03:43 EDT 2019<EOT>: text header: waiting for 2 byte(s)
     [java] Sat Jun 01 22:03:47 EDT 2019<EOT>: timeout sending [enable self_stimulation] giving up: java.util.concurrent.TimeoutException
     [java] Sat Jun 01 22:03:47 EDT 2019<EOT>: Sending [enable self_stimulation]
     [java] Sat Jun 01 22:03:48 EDT 2019<EOT>: ConnectionWatchdog.reconnectTimer restarting
     [java] Sat Jun 01 22:03:48 EDT 2019<EOT>: text header: timeout. Got only 0
     [java] Sat Jun 01 22:03:48 EDT 2019<EOT>: Sending packet 45 65 6E 61 62 6C 65 20 73 65 6C 66 5F 73 74 69 6D 75 6C 61 74 69 6F 6E 
     [java] Sat Jun 01 22:03:48 EDT 2019<EOT>: execute header: waiting for 2 byte(s)
     [java] Sat Jun 01 22:03:53 EDT 2019<EOT>: execute header: timeout. Got only 0
     [java] Sat Jun 01 22:03:53 EDT 2019<EOT>: Sending packet 45 65 6E 61 62 6C 65 20 73 65 6C 66 5F 73 74 69 6D 75 6C 61 74 69 6F 6E 
     [java] Sat Jun 01 22:03:53 EDT 2019<EOT>: execute header: waiting for 2 byte(s)
     [java] Sat Jun 01 22:03:57 EDT 2019<EOT>: No confirmation in 500
     [java] Sat Jun 01 22:03:57 EDT 2019<EOT>: Command [enable self_stimulation] executed in 20001
     [java] Sat Jun 01 22:03:57 EDT 2019<EOT>: Sending command [disable cylinder_cleanup]
     [java] Sat Jun 01 22:03:57 EDT 2019<EOT>: timeout sending [enable self_stimulation] giving up: java.util.concurrent.TimeoutException
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: Sending [enable self_stimulation]
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: execute header: timeout. Got only 0
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: postMessage SerialManager: Restarting serial IO
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: postMessage SerialManager: Opening port: COM4
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: Opening COM4 @ 115200
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: ERROR Port name - COM4; Method name - openPort(); Exception type - Port not found.
     [java] CONNECTION FAILED, did you specify the right port name?
     [java] Exception in thread "communication executor1" org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: Error while purge: jssc.SerialPortException: Port name - COM4; Method name - purgePort(); Exception type - Port not opened.
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: CLOSING PORT...
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: Error closing port: jssc.SerialPortException: Port name - COM4; Method name - closePort(); Exception type - Port not opened.
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: Sending packet 45 65 6E 61 62 6C 65 20 73 65 6C 66 5F 73 74 69 6D 75 6C 61 74 69 6F 6E 
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: execute: executeCommand failed: java.io.IOException: jssc.SerialPortException: Port name - COM4; Method name - writeBytes(); Exception type - Port not opened.
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: CLOSING PORT...
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: Error closing port: jssc.SerialPortException: Port name - COM4; Method name - closePort(); Exception type - Port not opened.
     [java]     at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:196)
     [java]     at java.lang.Runtime.exit(Runtime.java:107)
     [java]     at java.lang.System.exit(System.java:971)
     [java]     at com.rusefi.io.LinkManager$1.onConnectionFailed(LinkManager.java:27)
     [java]     at com.rusefi.io.serial.PortHolder.openPort(PortHolder.java:43)
     [java]     at com.rusefi.io.serial.SerialConnector$2.run(SerialConnector.java:41)
     [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     [java]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     [java]     at java.lang.Thread.run(Thread.java:748)
     [java] jssc.SerialPortException: Port name - COM4; Method name - readBytes(); Exception type - Port not opened.
     [java]     at jssc.SerialPort.checkPortOpened(SerialPort.java:878)
     [java]     at jssc.SerialPort.readBytes(SerialPort.java:694)
     [java]     at com.rusefi.io.serial.SerialPortReader.progressiveSleepRead(SerialPortReader.java:50)
     [java]     at com.rusefi.io.serial.SerialPortReader.access$000(SerialPortReader.java:15)
     [java]     at com.rusefi.io.serial.SerialPortReader$1.run(SerialPortReader.java:28)
     [java]     at java.lang.Thread.run(Thread.java:748)
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: Stopping text pull
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: Got confirmation in 21624ms
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: postMessage CommandQueue: Took 3 attempts
     [java] Sat Jun 01 22:03:58 EDT 2019<EOT>: Sending [disable cylinder_cleanup]
     [java] Sat Jun 01 22:03:59 EDT 2019<EOT>: Got confirmation in 2123ms
     [java] Sat Jun 01 22:03:59 EDT 2019<EOT>: Command [disable cylinder_cleanup] executed in 2123
     [java] Sat Jun 01 22:03:59 EDT 2019<EOT>: Sending command [set mock_map_voltage 1]
     [java] Sat Jun 01 22:03:59 EDT 2019<EOT>: Sending [set mock_map_voltage 1]
     [java] Sat Jun 01 22:03:59 EDT 2019<EOT>: Got confirmation in 500ms
     [java] Sat Jun 01 22:03:59 EDT 2019<EOT>: Command [set mock_map_voltage 1] executed in 500
     [java] Sat Jun 01 22:03:59 EDT 2019<EOT>: Sending command [set mock_vbatt_voltage 2.2]
     [java] Sat Jun 01 22:03:59 EDT 2019<EOT>: Sending [set mock_vbatt_voltage 2.2]
     [java] Sat Jun 01 22:04:00 EDT 2019<EOT>: Got confirmation in 500ms
```

**Comment by rusefi** [comment]
Previous issue was unreliable flashing - definitely different from unreliable serial connectivity

unreliable flashing could have been resolved by changing OpenOCD reset settings - https://github.com/rusefi/rusefi/commit/21674c00d3e6f1fa12d8d352972ac4093a24d45f

**Comment by rusefi** [comment]
this issue is NOT specific to the compiler - I've downgraded new build server to 2017q4 and still have the issue

I've set ANOTHER instance on build server on the living room TV desktop and it's reliable on the living room desktop. This is not nice :(

**Comment by rusefi** [comment]
same VCP driver 1.3.1.0 :(

**Comment by rusefi** [comment]
Same AdoptOpenJDK 1.8.0_212 64 bit java

**Comment by rusefi** [comment]
Works on new build server using USB-TTL instead of ST VCP.

**Comment by rusefi** [comment]
planning to also try https://www.amazon.com/gp/product/B01G85LFEK

**Comment by rusefi** [comment]
Same issue with https://www.amazon.com/gp/product/B01G85LFEK :( So, this is NOT related to motherboard controller. My biggest fear is that faster CPU is triggering some threading defect in who knows what later of which part of this :(

Still need help: looking for someone with a FAST device to try
```
misc/jenkins/functional_test_and_build_bundle/run.bat 
```
with discoveryf4 connected, make+arm gcc + ant + java installed

**Comment by rusefi** [comment]
between integration server migration to Windows 10 and #849 things seem to be resolved, closing issue for now
