### ISSUE TITLE
gcc 2019 q3 fails integration testing

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#886]
We seem to have reproducible issue with 8-2019-q3-update windows compiler

10 out of 12 times it's the same error on a pretty simple test towards the end of integration testing suite. Same exact error in same exact spot. One out of 12 times test has passed, one out of 12 test showing different error.

```[java] 2019-07-14_14_03_06_265<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.50 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_265<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_265<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_265<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_266<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_266<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.50 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_266<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_266<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_266<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_266<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_266<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.50 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_266<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_266<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_266<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.50 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=952476672.00 expected from 0.99 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=952476672.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=952476672.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=952476672.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_267<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=2147483647.47 expected from 0.99 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=2147483647.47 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_268<EOT>: postMessage EngineState: time=678 index=0: gap=2147483647.47 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=2147483647.47 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=6163640.00 expected from 1.00 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=6163640.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=6163640.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_269<EOT>: postMessage EngineState: time=678 index=0: gap=6163640.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=-0.00 expected from 0.99 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=-0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=-0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=-0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_270<EOT>: postMessage EngineState: time=678 index=0: gap=6160200.00 expected from 1.00 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=6160200.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=6160200.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=6160200.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=2147483647.47 expected from 0.99 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=2147483647.47 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=2147483647.47 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=2147483647.47 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 1.60 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_271<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 0.99 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_272<EOT>: postMessage EngineState: time=678 index=0: gap=0.00 expected from 1.00 to 0.00 error=(null)
     [java] 2019-07-14_14_03_06_306<EOT>: got next chart in 60001ms for engine_type 28
     [java] java.lang.IllegalStateException: Chart timeout: 60
     [java]     at com.rusefi.TestingUtils.getEngineChart(TestingUtils.java:144)
     [java]     at com.rusefi.TestingUtils.getNextWaveChart(TestingUtils.java:115)
     [java]     at com.rusefi.TestingUtils.nextChart(TestingUtils.java:108)
     [java]     at com.rusefi.AutoTest.testMazda626(AutoTest.java:139)
     [java]     at com.rusefi.AutoTest.mainTestBody(AutoTest.java:54)
     [java]     at com.rusefi.RealHwTest.runRealHardwareTest(RealHwTest.java:62)
     [java]     at com.rusefi.RealHwTest.main(RealHwTest.java:26)```

![image](https://user-images.githubusercontent.com/7377949/61186374-6683cc80-a632-11e9-8b0c-888c707af691.png)

**Comment by rusefi** [comment]
See also #646

**Comment by rusefi** [comment]
One time error:
``` [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: msg,FATAL error: handleCycleStart,
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: postMessage EngineState: FATAL error: handleCycleStart
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: Sending packet 4F 00 00 64 01 
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: output channels header: waiting for 2 byte(s)
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: IncomingDataBuffer: 256 byte(s) arrived
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: output channels body: waiting for 361 byte(s)
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: IncomingDataBuffer: 107 byte(s) arrived
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: Sending packet 47 
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: text header: waiting for 2 byte(s)
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: IncomingDataBuffer: 7 byte(s) arrived
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: text body: waiting for 5 byte(s)
     [java] Sun Jul 14 12:56:57 EDT 2019<EOT>: FAILURE: Not true: Fatal not expected
     [java] java.lang.IllegalStateException: Not true: Fatal not expected
     [java]     at com.rusefi.TestingUtils.fail(TestingUtils.java:52)
     [java]     at com.rusefi.TestingUtils.assertTrue(TestingUtils.java:27)
     [java]     at com.rusefi.TestingUtils.assertNull(TestingUtils.java:104)
     [java]     at com.rusefi.AutoTest.sendCommand(AutoTest.java:435)
     [java]     at com.rusefi.AutoTest.sendCommand(AutoTest.java:431)
     [java]     at com.rusefi.AutoTest.setEngineType(AutoTest.java:131)
     [java]     at com.rusefi.AutoTest.test2003DodgeNeon(AutoTest.java:146)
     [java]     at com.rusefi.AutoTest.mainTestBody(AutoTest.java:42)
     [java]     at com.rusefi.RealHwTest.runRealHardwareTest(RealHwTest.java:62)
     [java]     at com.rusefi.RealHwTest.main(RealHwTest.java:26)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java]     at java.lang.reflect.Method.invoke(Method.java:498)```

**Comment by rusefi** [comment]
File from jenkins job
[build.zip](https://github.com/rusefi/rusefi/files/3390290/build.zip)

**Comment by rusefi** [comment]
Hmm, now it looks like integration testing suddenly got unreliable :( Reverted to 2017 compiler and still see same issue :(

**Comment by rusefi** [comment]
Looks like gcc 8 has nothing to do with the problem, looks like naked ICU pins were catching some EMI and there was a coincidence with gcc migration.

Just added custom logic to ignore hardware ICU pins and things look good now.
